# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baeba0e8dfad97c2eda77a06f6fef809504c0daed1b50ca37d2a97845c8479e5bb2d8d9461b1bf739e4d212daf548800a47f214db5cdc70fb63790e3347287bc

test:
  secret_key_base: 8b17c9fe1698841482009ecda15781eeb49c57795e35c2c0babbe88f2e4b4fce9f0e5f3249e52c7c54bfe5e3554f874f5699d0082a871e5ec9dce8429c8d44ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
